export { Enemy } from './model/enemy'
export { BetrayalEnemy, UnusualEnemy, GuardianshipEnemy } from './model/understandingWeakEnemies'
export { ViolenceEnemy, BeingRidiculedEnemy, DoctorsEnemy } from './model/careWeakEnemies'
export { DarknessEnemy, AdultsEnemy } from './model/patienceWeakEnemies'
export { NewPlacesEnemy, MomDisappearEnemy, LonelinessEnemy } from './model/attentionWeakEnemies'
